package com.formationcloud.platform.model;

public enum TypeNotification {
	NOUVELLE_FORMATION, EVALUATION_DISPONIBLE, INSCRIPTION_VALIDEE,
	INSCRIPTION_REFUSEE, CERTIFICAT_OBTENU, NOUVELLE_INSCRIPTION, SEANCE_PLANIFIEE, SEANCE_MODIFIEE,
	TP_PUBLIE, TP_CORRIGE, NOUVELLE_SOUMISSION_TP, PRESENCE_A_COMPLETER, SEANCE_RAPPEL,
	TP_DEADLINE_PROCHE, TP_EN_RETARD, INSCRIPTION_EN_ATTENTE_ADMIN, FORMATION_ASSIGNEE,
	AUTRE
}